name: Proof HTML
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./
          check_html: true
      - uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./css/
          check_css: true